In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([[1,2,3,4],[1,2,3,4]])
print(b)

[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
c=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(c)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [ ]:
#dimensions
a.ndim

1

#to check the dimensionality
#either one or two or three


In [ ]:
b.ndim

2

In [ ]:
c.ndim

3

In [ ]:
#shape
b.shape

(2, 4)

#it will show how many rows and columns represent in the array


In [ ]:
#checking data type
b.dtype
c.dtype

dtype('int64')

In [ ]:
#itemsize
b.itemsize

8

In [ ]:
#totalsize
b.nbytes

64

#multiplty the list with itemsize
ie 8*totaln numbers in list is 8
#so we got 64 total bytes


In [ ]:
#acessing arrays with slicing
d=np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
d

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [ ]:
d[1,2]#(1 is row , 2 is columnn)

3

In [ ]:
d[1,3]

4

In [ ]:
d[0:1] # the total row

array([[1, 2, 3, 4, 5, 6, 7]])

In [ ]:
d[1]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#specific total column #metion comma after coln
d[:,2]

array([3, 3])

In [ ]:
d[:,4]

array([5, 5])

In [ ]:
#zeros
d=np.zeros((2,3)) #rows,columns
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#ones
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
d=np.ones((2,4,3)) #2 blocks,4 rows,3 elements
d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
d=np.zeros((3,4,2))
d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
d=np.full((2,3),99) #fill total blocks with number 99
d

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
#random
d=np.random.rand(2,3)
d

array([[0.8834887 , 0.4541332 , 0.55728295],
       [0.24047078, 0.75982369, 0.48318221]])

In [ ]:
#arange
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [ ]:
#identity
d=np.identity(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#copy
a=np.array([1,2,3,4])
b=a.copy()
b[0]=12
b

array([12,  2,  3,  4])

In [ ]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=12
a

array([1, 2, 3, 4])

In [ ]:
#mathematical operations
a=np.array([1,2,3,4,5])
print(a+2)

[3 4 5 6 7]


In [ ]:
print(a*2)

[ 2  4  6  8 10]


In [ ]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [ ]:
#accesing elements with indexing
list_array=([1,2,3,4])
print(list_array[2])


3


In [ ]:
#boardcasting
one=np.array([1,2,3,4])
two=np.array([1,2,3,4])
one+two


array([2, 4, 6, 8])

In [ ]:
one.shape

(4,)

In [ ]:
two.shape

(4,)

In [ ]:
#array manipulation
one=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
two=one.reshape(3,2,2) #3 blocks,2 rows,2 columns
print(two)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#statistical way
a=np.array([1,2,3,4,5,6])
print(np.mean(a))

3.5


In [ ]:
print(np.median(a))

3.5


In [ ]:
print(np.std(a))

1.707825127659933
